---

# port: 4000
# host: 0.0.0.0
# safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Amazon Review Dasaset Analysis"
keywords:    "Social Graph, Amazon, github, dataset, Analysis"
description: "An analysis of the Amazon Review Dataset"
source_link: "https://github.com/t413/SinglePaged"
favicon:     "img/Amazon_favicon.png"

### template colors, used site-wide via css ###
colors:
  black:         '#111111'
  white:         '#f8f8f8'
  blue:          '#49a7e9'
  green:         '#9bcf2f'
  purple:        '#c869bf'
  orange:        '#fab125'
  turquoise:     '#0fbfcf'
  amazon_yellow: '#ffa700'

kramdown:
  auto_ids:  false
